### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by ravijk** [pink-tie/JMSSerializerServiceProvider#12]
Does not mention that "jms/serializer-service-provider" is required and it gets confusing as Silex also has a ServiceProvider as part of  Provider package.

 "require": { "jms/serializer-service-provider": "dev-develop"}

**Comment by ravijk** [comment]
Actually this does not work "require": { "jms/serializer-service-provider": "dev-develop"}

I get the following errors 

 Problem 1
    - Can only install one of: jms/serializer-bundle[dev-master, 0.9.0].
    - Can only install one of: jms/serializer-bundle[0.9.0, dev-master].
    - jms/serializer-service-provider dev-develop requires jms/serializer-bundle 0.9.\* -> satisfiable by jms/serializer-bundle[0.9.0].
    - Installation request for jms/serializer-service-provider dev-develop -> satisfiable by jms/serializer-service-provider[dev-develop].
    - Installation request for jms/serializer-bundle dev-master -> satisfiable by jms/serializer-bundle[dev-master].

Unsure what is the correct way to install SerializerServiceProvider.  My Composer.json looks something like this 

"require": {
    "silex/silex": "1._"
    , "symfony/yaml": "2.3._"
    , "symfony/config": "2.3.*"
    , "symfony/translation": "~2.3"
    , "jdesrosiers/silex-swagger-provider": "~1.0"
    , "jdesrosiers/silex-cors-provider": "~0.1"
    , "monolog/monolog": ">=1.0.0"
    , "symfony/browser-kit": ">=2.3,<2.4-dev"
    , "jms/serializer-bundle": "dev-master"
    , "jms/serializer-service-provider": "dev-develop"
  },

**Comment by marijn** [comment]
This service provider is not compatible with the 1.0 release of JMS serializer. If you need compatibility with 1.0 than you best checkout [this suggestion](https://github.com/pink-tie/JMSSerializerServiceProvider/issues/8#issuecomment-20622542).

Otherwise change the version requirement for `jms/serializer-bundle` to `0.9.*`.

**Comment by 0-vortex** [comment]
also add this before registering:

Doctrine\Common\Annotations\AnnotationRegistry::registerAutoloadNamespace(
    'JMS\Serializer\Annotation',
    root . '/vendor/jms/serializer/src');
